# Use an official MySQL 8.0 image as the base

FROM mysql:8.0

# Set a default value for the environment variable
ARG ENV_FILE= .env

# Copy the .env file to the container
COPY $ENV_FILE /app/.env

# Copy the SQL initialization script to the container
COPY init.sql /docker-entrypoint-initdb.d/
